### ISSUE TITLE
多个tg账号的权限问题[FR] 

### ISSUE THREAD

**Issue by shzxm** [ehForwarderBot/efb-wechat-slave#112]
多tg账号使用过程中 
个人config.yaml中

admins:
- 账号1
- 账号2

貌似

第一个账号为 admin 权限

第二个账号为 user 权限

但是 因为存在多账号使用的情况 

user权限的账号不能收到 所有的信息

那么是不是可以把admins和users分开

希望收到所有信息的归为admins

这样bot默认把所有信息同时发给两个账号 

users账号保存为原本的权限

只有在回复的时候显示相关信息

示例
账号1 收到的信息
![image](https://user-images.githubusercontent.com/9905297/103369146-54d30500-4b04-11eb-9438-fb2d27fc0f27.png)

如果账号2 也为 admins权限
希望 也能收到账号1 现在收到的信息

但是目前 账号2 没有反应

**Comment by shzxm** [comment]
> 多tg
> 账号使用过程中个人config.yaml中
> 
> 管理员：
> 
> * 账号1
> * 账号2
> 
> 貌似
> 
> 第一个账号为admin权限
> 
> 第二个账号为用户权限
> 
> 但是因为存在多账号使用的情况
> 
> 用户权限的账号不能收到所有的信息
> 
> 那么是不是可以把admins和users分开
> 
> 希望收到所有信息的归为admins
> 
> 这样的机器人唯一把所有信息同时发给两个账号
> 
> 用户账号保存为原本的权限
> 
> 只有在回复的时候显示相关信息
> 
> 示例
> 账号1收到的信息
> ![图片](https://user-images.githubusercontent.com/9905297/103369146-54d30500-4b04-11eb-9438-fb2d27fc0f27.png)
> 
> 如果账号2也为admins权限
> 希望也能收到账号1现在收到的信息
> 
> 但是目前账号2没有反应


最终的配置文件为

![Uploading image.png…]()

**Comment by blueset** [comment]
ETM 那边只有「Bot 管理员」这一个清单。

根据设计，只有第 0 个管理员可以收到 bot 发来的私信（参见[文档](https://github.com/ehForwarderBot/efb-telegram-master/blob/master/readme_translations/zh_CN.rst#%E7%94%A8%E6%B3%95)）。由于数据库设计原因，目前结构无法实现将同一条消息发送给多个管理员。如有相关需求，请尝试将会话绑定到 Telegram 群组，并将所有管理员加入群。

**Comment by shzxm** [comment]
我的妈？你2点还不睡？

**Comment by blueset** [comment]
> 我的妈？你2点还不睡？
> – @shzxm 

我的妈？你 4 点还不睡？

😂
