### ISSUE TITLE
[FR] 已有绕过web 登录的方式

### ISSUE THREAD

**Issue by suikaremilia** [ehForwarderBot/efb-wechat-slave#115]
2017年以来web端登录微信越来越困难，但近来有了绕开微信限制的方法，如下：

https://wechaty.js.org/2021/04/13/wechaty-uos-web/

https://github.com/wechaty/wechaty-puppet-wechat

原理好像就是改了个标头

是否可以更新一下，以便让更多的人可以把efb用起来，谢谢！

**Comment by blueset** [comment]
[EWS 2.0.5](https://github.com/ehForwarderBot/efb-wechat-slave/releases/tag/v2.0.5) 已追加 UOS 请求头，基于 littlecodersh/itchat#935。
