### ISSUE TITLE
可以弄成平板登陆吗

### ISSUE THREAD

**Issue by sonrixmomo** [ehForwarderBot/efb-wechat-slave#120]
可以弄成平板登陆吗

**Comment by blueset** [comment]
目前还没有发现免费能用的接口。如果有发现的话欢迎提供线索。

**Comment by l-we** [comment]
有一个 Windows的注入方式，免费，但是配合Linux太麻烦，

**Comment by blueset** [comment]
> 有一个 Windows的注入方式，免费，但是配合Linux太麻烦，

至少比 macOS 注入还容易部署一点。

**Comment by sonrixmomo** [comment]
> > 有一个 Windows的注入方式，免费，但是配合Linux太麻烦，
> 
> 至少比 macOS 注入还容易部署一点。

能实现，但是麻烦对吧？

**Comment by blueset** [comment]
> 能实现，但是麻烦对吧？

如果有足够合理可以调用的接口，实现应该就没什么问题。Windows 的话部署的局限性肯定是会更大。

**Comment by Gikkingenhanaya** [comment]
2021年八月的时候微信支持ipad登录windows版客户端同时在线，那么现在能在开启efb转发的时候登录ipad版微信吗

**Comment by blueset** [comment]
Closing staled issue.
