### ISSUE TITLE
[FR] 免打扰 chat 处理优化

### ISSUE THREAD

**Issue by amosbird** [ehForwarderBot/efb-wechat-slave#124]
## Is your feature request related to a problem? Please describe. 您的建议具体与什么有关？  

当前所有的消息都会被汇聚到 bot chat 中，包括免打扰的群聊，消息太多。单独为白名单 chat 进行 link 需要较多的维护成本，且每次新增好友需要更新。

## Describe the solution you'd like 希望的解决方案

增加选项将所有免打扰的 chat link 到一个单独的群中

## Describe alternatives you've considered 考虑过的替代方案  

增加选项拒收所有免打扰的消息

**Comment by amosbird** [comment]
@blueset 请问这个 FR 应该属于哪个 repo 呢？

**Comment by blueset** [comment]
ETM 已有拒收此类消息的设置，可以尝试一下。选项名是 `message_muted_on_slave`。

> 请问这个 FR 应该属于哪个 repo 呢？
这个本是 ETM 相关的逻辑，不过所有中文的 issue 都汇集到这里了，就只打了个标签。
