### ISSUE TITLE
[BUG] 通过pip3更新后再次运行报错

### ISSUE THREAD

**Issue by GrassBlock1** [ehForwarderBot/efb-wechat-slave#128]
### 版本信息 Version Info

```
EH Forwarder Bot
Version: 2.1.1
Python version:
3.10.1

Master channel:
    EFB Telegram Master Channel

Slave channel:
    efb-wechat-slave

Middleware:
    none
```

### 问题描述 Describe the bug

 昨天遇到 #126 提到的问题 准备在主端运行时使用pip3更新
更新后再次运行时,报错无法运行
### 重现步骤 To Reproduce

在主端无法正常登陆wechat时运行了
` pip3 install efb-wechat-slave --upgrade `
并对 ehforwarderbot 也进行了同样的操作。
使用 `ehforwarderbot --verbose ` 运行时出现了以下错误。
### 截图 Screenshots

见输出日志

### Verbose 日志 Log
<details>
<summary>Verbose 日志</summary>

```
请在下方贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。

【贴在下面】
https://pastebin.com/P27WDs7F


【贴在上面】

```
 
</details>

## 备注 Additional context
如果不是该从端问题请告知，会自行删除。

**Comment by GuangDai** [comment]
我也是这样，你去网页版看一下，多半是封了

**Comment by blueset** [comment]
Duplicate of #126
