### ISSUE TITLE
[BUG] 无法接收微信语音消息

### ISSUE THREAD

**Issue by skyfore** [ehForwarderBot/efb-wechat-slave#133]
### 版本信息 Version Info

```
EH Forwarder Bot
版本: 2.1.1
Python 版本:
3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### 问题描述 Describe the bug

TG 无法接收微信语音消息，通过 `journalctl -f -u efb.service` 查看消息日志发现报错信息如下

![image](https://user-images.githubusercontent.com/7485049/153534190-7e15014f-6d91-45af-993f-d6c088fbdf60.png)

### Verbose 日志 Log
<details>
<summary>Verbose 日志</summary>

```
请在下方贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。

【贴在下面】



【贴在上面】

```
 
</details>

**Comment by blueset** [comment]
服务器使用的 FFmpeg 可能没有 libopus 支持。请参阅 FFmpeg 的文档寻找 libopus 支援的安装方式。
